config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :posts do
    member do 
      put "like",    to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
  end
  
  def new
    @post = current_user.posts.build
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end
  
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to :back
  end
  
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body, :date)
  end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Được tạo <strong><%= time_ago_in_words(comment.created_at) %> trước</strong></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nhật ký Online</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body background = "https://uphinhnhanh.com/images/9852101_Hinh_nen_de_thuong_4.jpg">
  <div class="container" >
    <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Nhật Ký Online", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        	<% if user_signed_in? -%>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to 'Tạo nhật ký mới', new_post_path %></li>
							<li><%= link_to 'Chỉnh sửa thông tin', edit_user_registration_path %></li>
							<li><%= link_to 'Đăng xuât', destroy_user_session_path, :method => :delete %></li>
						</ul>
					<% else -%>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to 'Đăng ký', new_user_registration_path %></li>
							<li><%= link_to 'Đăng nhập', new_user_session_path %></li>
						</ul>
					<% end -%>
        </nav>
      </div>
    </div>
  </header>
  	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-12 center-block">
				<%= yield %>
			</div>
		</div>
	</div>
  </div>


</body>
</html>

app/views/posts/edit.html.erb
<h1>Chỉnh sửa nhật ký</h1>
<%= form_for @post do |f| %>
    <%= f.label :"Tiêu đề" %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :"Nội dung nhật ký" %><br>
    <%= f.text_area :body %><br>
    
    <%= f.label :"Ngày" %><br>
    <%= f.text_area :date %><br>
    <br>
    <%= f.submit "Cập nhật" %>
    <% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <div>
        <%= post.date %>
    </div>
    <div>
        <%= truncate(post.body, :length =>500) %>
    </div>
    <div class="btn-group">
	    <%= link_to "Đọc thêm",  post , class: "btn btn-primary" %>
    </div>
    
    <div class="btn-group">
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Like
        <%= post.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Dislike
        <%= post.get_downvotes.size %>
      <% end %>
    </div>
    <hr size ="2px" color = "red" >
    
<% end %>

app/views/posts/new.html.erb
<h1>Nhật kí mới</h1>
<%= form_for @post do |f| %>
    <%= f.label :"Tiêu đề" %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :"Nội dung nhật ký" %><br>
    <%= f.text_area :body %><br>
    
    <%= f.label :"Ngày" %><br>
    <%= f.text_area :date %><br>
    <br>
    <div class="btn-group">
	    <%= f.submit "Tạo nhật ký", class: "btn btn-primary" %>
    </div>
    
    <% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>
<div>
    <%= @post.date %>
</div>
<div>
    <%= @post.body %>
</div>
<br>
<% if @post.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Chỉnh sửa', edit_post_path(@post), class: "btn btn-primary" %>
		<%= link_to 'Xóa', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
	</div>
<% end %>

<div class="btn-group pull-right">
  <%= link_to like_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    Like
    <%= @post.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down">
    Dislike
    <%= @post.get_downvotes.size %>
  <% end %>
</div>

<h3 class="comments_title">
  <%= @post.comments.count %> Comments
</h3>

<div id="comments">
  <%= render :partial => @post.comments %>
</div>
<%= simple_form_for [@post, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>